### ISSUE TITLE
[SECURITY] - Cert Manager Mandatory for Openshift 4.X

### ISSUE THREAD

**Issue by saravananindupriya-vendor** [some-natalie/kubernoodles#164]
## Describe the problem

A clear and concise description of the problem.

We are trying to setup ARC on Openshift 4.X. Can we install the ARC without using the cert-manager for openshift 4.X?

**Comment by some-natalie** [comment]
Hey @saravananindupriya-vendor, this question is best redirected to the upstream project (https://github.com/actions/actions-runner-controller) and already has a discussion [here](https://github.com/actions/actions-runner-controller/discussions/1347) about the topic.
